apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chain-rpc
  namespace: chain
spec:
  serviceName: chain-rpc
  replicas: 1
  selector:
    matchLabels:
      app: chain-rpc
  template:
    metadata:
      labels:
        app: chain-rpc
    spec:
      containers:
        - name: chain-rpc
          image: fluencelabs/chain-rpc:0.24.2
          ports:
            - containerPort: 8545
              name: rpc
          env:
            - name: LOCAL_CHAIN_BLOCK_MINING_INTERVAL
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: 8545
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: chain-rpc
  namespace: chain
spec:
  selector:
    app: chain-rpc
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
