apiVersion: batch/v1
kind: Job
metadata:
  name: subgraph-deploy
  namespace: chain
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
              - name: wait-graphnode
                image: busybox:1.36
                command: ["sh", "-c"]
                args:
                  - |
                    echo "Waiting for graph-node:8020..."
                    until nc -z graph-node 8020; do 
                      sleep 2
                    done
                    echo "graph-node is ready"
      containers:
        - name: subgraph-deploy
          image: fluencelabs/subgraph-deploy-script:0.24.2
          env:
            - name: GRAPHNODE_ADMIN_URL_LOCAL
              value: http://graph-node:8020
            - name: IPFS_URL
              value: http://ipfs:5001
