apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: chain-base
  namespace: flux-system
spec:
  interval: 5m
  path: ./app/chain/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m