apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-node
  namespace: chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-node
  template:
    metadata:
      labels:
        app: graph-node
    spec:
      containers:
        - name: graph-node
          image: fluencelabs/graph-node:v0.35.1
          ports:
            - containerPort: 8000
              name: query
            - containerPort: 8001
              name: index
            - containerPort: 8020
              name: admin
            - containerPort: 8030
              name: status
            - containerPort: 8040
              name: metrics
          env:
            - name: postgres_host
              value: pg-chain-rw
            - name: postgres_user
              value: graph-node
            - name: postgres_pass
              valueFrom:
                secretKeyRef:
                  name: pg-chain-graphnode
                  key: password
            - name: postgres_db
              value: app
            - name: ipfs
              value: ipfs:5001
            - name: ethereum
              value: local:http://chain-rpc:8545
            - name: GRAPH_LOG
              value: info
            - name: ETHEREUM_REORG_THRESHOLD
              value: "1"
            - name: ETHEREUM_ANCESTOR_COUNT
              value: "1"
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: graph-node
  namespace: chain
spec:
  selector:
    app: graph-node
  ports:
    - name: query
      port: 8000
      targetPort: 8000
    - name: index
      port: 8001
      targetPort: 8001
    - name: admin
      port: 8020
      targetPort: 8020
    - name: status
      port: 8030
      targetPort: 8030
    - name: metrics
      port: 8040
      targetPort: 8040